# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# from tkinter import *
# Explicit imports to satisfy Flake8


from pathlib import Path


from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import os

commands = [
    'gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-applications "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-windows "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings activate-window-menu "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings show-desktop "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings maximize "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings unmaximize "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings minimize "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings close "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings begin-move "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings begin-resize "['']"',
    'gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['']"'
]

for items in commands:
    os.system(items)

def datos_formulario(usuario, password):
    print(usuario,password)
    window.destroy()
    os.system("dconf reset -f /org/gnome/desktop/wm/keybindings/")

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/rootap/Documents/tk/Tkinter-Designer/login/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.attributes("-fullscreen", True)
window.attributes("-topmost", True)
window.configure(bg='black')
window.geometry("1922x1080")
window.configure(bg = "#617AFF")
window.protocol("WM_DELETE_WINDOW", False)


canvas = Canvas(
    window,
    bg = "#617AFF",
    height = 1080,
    width = 1952,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1335.0,
    564.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    bg="#617AFF",
    border=None,
    highlightthickness=None,
    command=lambda: datos_formulario(entry_1.get(),entry_2.get()),
    relief="flat"
)
button_1.place(
    x=1089.0,
    y=717.0,
    width=360.0,
    height=90.0
)

canvas.create_text(
    1033.0,
    240.0,
    anchor="nw",
    text="Hey Camper!",
    fill="#FFFFFF",
    font=("Roboto Bold", 80 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1269.0,
    595.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F1F5FF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1064.5,
    y=564.0,
    width=409.0,
    height=61.0
)

canvas.create_text(
    45.999999999999886,
    643.0,
    anchor="nw",
    text="#CAMPUSLANDS",
    fill="#FFFFFF",
    font=("Roboto Bold", 80 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1269.0,
    448.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F1F5FF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=1064.5,
    y=417.0,
    width=409.0,
    height=61.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    364.9999999999999,
    417.0,
    image=image_image_2
)

canvas.create_text(
    1067.0,
    525.0,
    anchor="nw",
    text="contraseña",
    fill="#FFFFFF",
    font=("Roboto Bold", 35 * -1)
)

canvas.create_text(
    1067.0,
    377.0,
    anchor="nw",
    text="usuarios",
    fill="#FFFFFF",
    font=("Roboto Bold", 35 * -1)
)
window.resizable(False, False)
window.mainloop()